name Deploy to Heroku

on
  push
    branches
      - main

jobs
  deploy
    runs-on ubuntu-latest

    steps
    - name Checkout code
      uses actionscheckout@v2

    - name Set up Python
      uses actionssetup-python@v2
      with
        python-version '3.10'

    - name Install dependencies
      run 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name Deploy to Heroku
      env
        HEROKU_API_KEY ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME ${{ secrets.HEROKU_APP_NAME }}
      run 
        curl httpscli-assets.heroku.cominstall.sh  sh
        heroku authtoken $HEROKU_API_KEY
        git remote add heroku httpsgit.heroku.com$HEROKU_APP_NAME.git
        git push heroku main
