name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Realiza o checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Passo 2: Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Passo 3: Instala as dependências do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Passo 4: Debug - Listar todos os arquivos e pastas no repositório
    - name: List files for debugging
      run: |
        echo "Listando arquivos e pastas no repositório:"
        ls -R

    # Passo 5: Adiciona o diretório 'app' ao PYTHONPATH
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

    # Passo 6: Executa os testes
    - name: Run tests
      run: |
        pytest
